server:
  port: 8090
spring:
  application:
    name: eblumbit
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/eblumbit_spring
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
  file:
    name: logs/compras-ventas.log
    logback:
    rollingpolicy:
      file-name-pattern: logs/compras-ventas-%d{yyyy-MM-dd}.log
      max-history: 30
      max-file-size: 10MB
      total-size-cap: 1GB
  level:
    root: INFO
    '[com.blumbit.eblumbit]': DEBUG
    '[org.springframework.web]': WARN
    '[org.hibernate]': WARN
application:
  jwt:
    secret-key: mysecretkey
    expiration: 900000 # 15 minutos
    refresh-expiration: 604800000 # 7 días
